repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --manifest-path rust/Cargo.toml --all -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --manifest-path rust/Cargo.toml --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]

      - id: sloc
        name: Update lines of code
        entry: bash -c './sloc.sh && git add LINES_OF_CODE.md'
        language: system
        always_run: true
        pass_filenames: false
