/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * JavaScript-facing HAI client.
 *
 * Constructor accepts a JSON config string. All methods return `Promise<string>`
 * containing JSON responses.
 */
export declare class HaiClient {
  /**
   * Create a new HaiClient from a config JSON string.
   *
   * If `jacs_config_path` is provided, loads a real JACS agent for
   * cryptographic signing. Otherwise falls back to a test-only provider.
   *
   * Config format: `{"base_url": "...", "jacs_id": "...", "jacs_config_path": "/path/to/jacs.config.json", "timeout_secs": 30, "max_retries": 3}`
   */
  constructor(configJson: string)
  hello(includeTest: boolean): Promise<string>
  register(optionsJson: string): Promise<string>
  registerNewAgent(optionsJson: string): Promise<string>
  rotateKeys(optionsJson: string): Promise<string>
  updateAgent(newAgentData: string): Promise<string>
  submitResponse(paramsJson: string): Promise<string>
  verifyStatus(agentId?: string | undefined | null): Promise<string>
  updateUsername(agentId: string, username: string): Promise<string>
  deleteUsername(agentId: string): Promise<string>
  sendEmail(optionsJson: string): Promise<string>
  sendSignedEmail(optionsJson: string): Promise<string>
  listMessages(optionsJson: string): Promise<string>
  updateLabels(paramsJson: string): Promise<string>
  getEmailStatus(): Promise<string>
  getMessage(messageId: string): Promise<string>
  getRawEmail(messageId: string): Promise<string>
  getUnreadCount(): Promise<string>
  markRead(messageId: string): Promise<void>
  markUnread(messageId: string): Promise<void>
  deleteMessage(messageId: string): Promise<void>
  archive(messageId: string): Promise<void>
  unarchive(messageId: string): Promise<void>
  replyWithOptions(paramsJson: string): Promise<string>
  forward(paramsJson: string): Promise<string>
  searchMessages(optionsJson: string): Promise<string>
  contacts(): Promise<string>
  fetchServerKeys(): Promise<string>
  signEmailRaw(rawEmailB64: string): Promise<string>
  verifyEmailRaw(rawEmailB64: string): Promise<string>
  saveAgreement(requestJson: string): Promise<string>
  searchAgreements(requestJson: string): Promise<string>
  getAgreement(agreementId: string): Promise<string>
  countersignAgreement(agreementId: string, requestJson: string): Promise<string>
  createAgreementV2(inputJson: string): Promise<string>
  applyAgreementV2(document: string, mutationJson: string): Promise<string>
  signAgreementV2(document: string, role: string): Promise<string>
  verifyAgreementV2(document: string): Promise<string>
  detectAgreementBranchConflict(baseDocument: string, leftDocument: string, rightDocument: string): Promise<string>
  mergeAgreementTranscriptBranches(baseDocument: string, leftDocument: string, rightDocument: string): Promise<string>
  resolveAgreementBranchConflict(baseDocument: string, previousDocument: string, sideBranchDocument: string, resolutionJson: string): Promise<string>
  signText(path: string, optsJson: string): Promise<string>
  verifyText(path: string, optsJson: string): Promise<string>
  signImage(inPath: string, outPath: string, optsJson: string): Promise<string>
  verifyImage(path: string, optsJson: string): Promise<string>
  extractMediaSignature(path: string, optsJson: string): Promise<string>
  createAttestation(paramsJson: string): Promise<string>
  listAttestations(paramsJson: string): Promise<string>
  getAttestation(agentId: string, docId: string): Promise<string>
  verifyAttestation(document: string): Promise<string>
  createEmailTemplate(optionsJson: string): Promise<string>
  listEmailTemplates(optionsJson: string): Promise<string>
  getEmailTemplate(templateId: string): Promise<string>
  updateEmailTemplate(templateId: string, optionsJson: string): Promise<string>
  deleteEmailTemplate(templateId: string): Promise<void>
  fetchRemoteKey(jacsId: string, version: string): Promise<string>
  fetchKeyByHash(hash: string): Promise<string>
  fetchKeyByEmail(email: string): Promise<string>
  fetchKeyByDomain(domain: string): Promise<string>
  fetchAllKeys(jacsId: string): Promise<string>
  verifyDocument(document: string): Promise<string>
  getVerification(agentId: string): Promise<string>
  verifyAgentDocument(requestJson: string): Promise<string>
  benchmark(name?: string | undefined | null, tier?: string | undefined | null): Promise<string>
  freeRun(transport?: string | undefined | null): Promise<string>
  proRun(optionsJson: string): Promise<string>
  enterpriseRun(): Promise<void>
  buildAuthHeader(): Promise<string>
  signMessage(message: string): Promise<string>
  signResponse(payloadJson: string): Promise<string>
  canonicalJson(valueJson: string): Promise<string>
  verifyA2AArtifact(wrappedJson: string): Promise<string>
  exportAgentJson(): Promise<string>
  jacsId(): Promise<string>
  baseUrl(): Promise<string>
  haiAgentId(): Promise<string>
  agentEmail(): Promise<string | null>
  setHaiAgentId(id: string): Promise<void>
  setAgentEmail(email: string): Promise<void>
  connectSse(): Promise<number>
  sseNextEvent(handle: number): Promise<string | null>
  sseClose(handle: number): Promise<void>
  connectWs(): Promise<number>
  wsNextEvent(handle: number): Promise<string | null>
  wsClose(handle: number): Promise<void>
  storeDocument(signedJson: string): Promise<string>
  signAndStore(dataJson: string): Promise<string>
  getDocument(key: string): Promise<string>
  getLatestDocument(docId: string): Promise<string>
  getDocumentVersions(docId: string): Promise<string>
  listDocuments(jacsType?: string | undefined | null): Promise<string>
  removeDocument(key: string): Promise<void>
  updateDocument(docId: string, signedJson: string): Promise<string>
  searchDocuments(query: string, limit: number, offset: number): Promise<string>
  queryByType(docType: string, limit: number, offset: number): Promise<string>
  queryByField(field: string, value: string, limit: number, offset: number): Promise<string>
  queryByAgent(agentId: string, limit: number, offset: number): Promise<string>
  storageCapabilities(): Promise<string>
  saveDocument(requestJson: string): Promise<string>
  saveMemory(content?: string | undefined | null): Promise<string>
  saveSoul(content?: string | undefined | null): Promise<string>
  getMemory(): Promise<string | null>
  getSoul(): Promise<string | null>
  storeTextFile(path: string): Promise<string>
  storeImageFile(path: string): Promise<string>
  /**
   * Fetch raw record bytes (no UTF-8 decode, no JSON parse). Returns a
   * Node `Buffer` (assignable to `Uint8Array`).
   */
  getRecordBytes(key: string): Promise<Buffer>
  conflictCreate(bodyJson: string): Promise<string>
  conflictUpdate(keyOrId: string, mutationJson: string): Promise<string>
  conflictGet(key: string): Promise<string>
  conflictList(limit: number, offset: number): Promise<string>
  conflictCheckReadiness(keyOrId: string): Promise<string>
}
