/* Generated by cbindgen -- do not edit manually. */

#ifndef HAIIGO_H
#define HAIIGO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Arc_HaiClientWrapper Arc_HaiClientWrapper;

typedef const struct Arc_HaiClientWrapper *HaiClientHandle;

/**
 * Retrieve the last error from `hai_client_new` as a JSON string.
 * Returns null if no error is stored. Caller must free the returned string
 * with `hai_free_string`.
 */
char *hai_last_error(void);

/**
 * Create a new HAI client from a config JSON string.
 * Returns an opaque handle. Caller must call `hai_client_free` when done.
 * On failure, returns null. Call `hai_last_error()` to get error details.
 */
HaiClientHandle hai_client_new(const char *config_json);

/**
 * Free a HAI client handle.
 */
void hai_client_free(HaiClientHandle handle);

/**
 * Free a string returned by any hai_* function.
 */
void hai_free_string(char *s);

char *hai_hello(HaiClientHandle handle, bool include_test);

char *hai_verify_status(HaiClientHandle handle, const char *agent_id);

char *hai_claim_username(HaiClientHandle handle, const char *agent_id, const char *username);

char *hai_update_username(HaiClientHandle handle, const char *agent_id, const char *username);

char *hai_fetch_remote_key(HaiClientHandle handle, const char *jacs_id, const char *version);

char *hai_benchmark(HaiClientHandle handle, const char *name, const char *tier);

char *hai_free_run(HaiClientHandle handle, const char *transport);

char *hai_enterprise_run(HaiClientHandle handle);

char *hai_build_auth_header(HaiClientHandle handle);

/**
 * Get the JACS ID of the client.
 * Returns a JSON envelope: `{"ok":"<jacs_id>"}` or `{"error":...}`.
 */
char *hai_jacs_id(HaiClientHandle handle);

char *hai_set_hai_agent_id(HaiClientHandle handle, const char *id);

char *hai_set_agent_email(HaiClientHandle handle, const char *email);

#endif  /* HAIIGO_H */
