#!/usr/bin/env bash
#
# generate_knowledge.sh — Copies jacsbook chapters, SDK READMEs, and JACS README
# into rust/haiai/docs/knowledge/ and generates rust/haiai/src/self_knowledge_data.rs
# with include_str!() references for compile-time embedding.
#
# Usage: ./scripts/generate_knowledge.sh
#
# Run from the haisdk repo root. Requires sibling ../JACS repo for jacsbook source.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JACS_ROOT="$(cd "$REPO_ROOT/../JACS" && pwd)"
JACSBOOK_SRC="$JACS_ROOT/jacs/docs/jacsbook/src"
SUMMARY="$JACSBOOK_SRC/SUMMARY.md"
KNOWLEDGE_DIR="$REPO_ROOT/rust/haiai/docs/knowledge"
DATA_FILE="$REPO_ROOT/rust/haiai/src/self_knowledge_data.rs"

if [ ! -f "$SUMMARY" ]; then
    echo "ERROR: SUMMARY.md not found at $SUMMARY" >&2
    echo "Ensure the JACS repo is at $JACS_ROOT" >&2
    exit 1
fi

# Clean and recreate knowledge directory
rm -rf "$KNOWLEDGE_DIR"
mkdir -p "$KNOWLEDGE_DIR/jacsbook"
mkdir -p "$KNOWLEDGE_DIR/haiai-sdk"
mkdir -p "$KNOWLEDGE_DIR/jacs"

# ── Parse SUMMARY.md and copy jacsbook files ──────────────────────

declare -a JACSBOOK_PATHS=()
declare -a JACSBOOK_TITLES=()

re='\[([^]]+)\]\(([^)]+\.md)\)'
while IFS= read -r line; do
    # Match lines like: - [Title](path.md) or   - [Title](dir/path.md)
    if [[ "$line" =~ $re ]]; then
        title="${BASH_REMATCH[1]}"
        rel_path="${BASH_REMATCH[2]}"

        src_file="$JACSBOOK_SRC/$rel_path"
        if [ -f "$src_file" ]; then
            # Create destination directory structure
            dest_file="$KNOWLEDGE_DIR/jacsbook/$rel_path"
            mkdir -p "$(dirname "$dest_file")"
            cp "$src_file" "$dest_file"

            JACSBOOK_PATHS+=("$rel_path")
            JACSBOOK_TITLES+=("$title")
        else
            echo "WARN: jacsbook file not found: $src_file (skipping)" >&2
        fi
    fi
done < "$SUMMARY"

echo "Copied ${#JACSBOOK_PATHS[@]} jacsbook chapters"

# ── Copy SDK READMEs ──────────────────────────────────────────────

declare -a README_SRCS=(
    "$REPO_ROOT/README.md"
    "$REPO_ROOT/python/README.md"
    "$REPO_ROOT/node/README.md"
    "$REPO_ROOT/go/README.md"
    "$REPO_ROOT/rust/haiai/README.md"
    "$REPO_ROOT/rust/haiai-cli/README.md"
    "$REPO_ROOT/rust/hai-mcp/README.md"
    "$REPO_ROOT/fixtures/README.md"
)

declare -a README_NAMES=(
    "root.md"
    "python.md"
    "node.md"
    "go.md"
    "haiai.md"
    "haiai-cli.md"
    "hai-mcp.md"
    "fixtures.md"
)

declare -a README_TITLES=(
    "HAIAI SDK"
    "HAIAI Python SDK"
    "HAIAI Node SDK"
    "HAIAI Go SDK"
    "HAIAI Rust Library"
    "HAIAI CLI"
    "HAI MCP Server"
    "HAIAI Fixtures"
)

readme_count=0
for i in "${!README_SRCS[@]}"; do
    src="${README_SRCS[$i]}"
    name="${README_NAMES[$i]}"
    if [ -f "$src" ]; then
        cp "$src" "$KNOWLEDGE_DIR/haiai-sdk/$name"
        ((readme_count++))
    else
        echo "WARN: README not found: $src (skipping)" >&2
    fi
done

echo "Copied $readme_count SDK READMEs"

# ── Copy JACS root README ────────────────────────────────────────

if [ -f "$JACS_ROOT/README.md" ]; then
    cp "$JACS_ROOT/README.md" "$KNOWLEDGE_DIR/jacs/README.md"
    echo "Copied JACS root README"
else
    echo "WARN: JACS README not found at $JACS_ROOT/README.md (skipping)" >&2
fi

# ── Generate self_knowledge_data.rs ──────────────────────────────

cat > "$DATA_FILE" << 'HEADER'
//! Auto-generated by scripts/generate_knowledge.sh -- do not edit.
//! Regenerate: ./scripts/generate_knowledge.sh

/// (relative_path, title, content_via_include_str)
pub static CHAPTERS: &[(&str, &str, &str)] = &[
HEADER

# Helper to escape strings for Rust (double quotes and backslashes)
escape_rust_str() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

# Jacsbook entries
for i in "${!JACSBOOK_PATHS[@]}"; do
    path="${JACSBOOK_PATHS[$i]}"
    title="$(escape_rust_str "${JACSBOOK_TITLES[$i]}")"
    cat >> "$DATA_FILE" << ENTRY
    ("jacsbook/$path", "$title",
     include_str!("../docs/knowledge/jacsbook/$path")),
ENTRY
done

# SDK README entries
for i in "${!README_NAMES[@]}"; do
    name="${README_NAMES[$i]}"
    title="$(escape_rust_str "${README_TITLES[$i]}")"
    dest="$KNOWLEDGE_DIR/haiai-sdk/$name"
    if [ -f "$dest" ]; then
        cat >> "$DATA_FILE" << ENTRY
    ("haiai-sdk/$name", "$title",
     include_str!("../docs/knowledge/haiai-sdk/$name")),
ENTRY
    fi
done

# JACS root README
if [ -f "$KNOWLEDGE_DIR/jacs/README.md" ]; then
    cat >> "$DATA_FILE" << 'ENTRY'
    ("jacs/README.md", "JACS",
     include_str!("../docs/knowledge/jacs/README.md")),
ENTRY
fi

# Close the array
echo "];" >> "$DATA_FILE"

total=$((${#JACSBOOK_PATHS[@]} + readme_count))
if [ -f "$KNOWLEDGE_DIR/jacs/README.md" ]; then
    ((total++))
fi

echo "Generated $DATA_FILE with $total entries"
echo "Done."
